services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
      - "8071:8071"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./data:/var/lib/odoo
    environment:
      - HOST=host.docker.internal
      - USER=odoo_user       
      - PASSWORD=xcWI3128
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
