[options]
; Database Configuration
admin_passwd = admin_password_super_rahasia
db_host = host.docker.internal
db_port = 5432
db_user = odoo_user
db_password = xcWI3128
db_name = odoo

; Paths
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; Performance & Logs
workers = 0
limit_time_cpu = 600
limit_time_real = 1200
log_level = info